name: Build Hermes
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/
      - name: Update Core Index with Teensy URL
        run: |
          arduino-cli core update-index --additional-urls https://www.pjrc.com/teensy/package_teensy_index.json
      - name: Install Teensy Core
        run: |
          arduino-cli core install teensy:avr --additional-urls https://www.pjrc.com/teensy/package_teensy_index.json
      - name: Install ILI9341_t3n Library
        run: |
          arduino-cli lib install ILI9341_t3n
      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn teensy:avr:teensy41 .
